version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
    depends_on:
      - db
    volumes:
      - ./hexagon.log:/app/hexagon.log

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=hexagon
      - POSTGRES_USER=hexagon_user
      - POSTGRES_PASSWORD=hexagon_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
