name: hexagon-api
services:
  - name: api
    source_dir: /
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: CLERK_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CLERK_PUBLISHABLE_KEY
        scope: RUN_TIME

databases:
  - name: db
    engine: PG
    version: "14"
    size: basic-xs
    num_nodes: 1
