from schemas import HabitRead, HabitCreate
from database import Base, engine, get_db
from fastapi import FastAPI
from models import Habit
from typing import List
import logging

from logging_config import configure_logging
# Override POST /habit to enforce unique title and return autogenerated id
from fastapi import HTTPException, status, Depends, APIRouter
from fastapi.responses import JSONResponse
from sqlalchemy.orm import Session

Base.metadata.create_all(bind=engine)
from middlewares import register_middleware
app = FastAPI(title="Habit Tracker API")
logger = logging.getLogger("hexagon")

logger.info("Starting the app...")

register_middleware(app)

router = APIRouter()

@router.get("/")
async def root():
    return {"message": "Welcome to Hexagon API"}

@router.get("/health")
async def healthcheck():
    return JSONResponse(content={"status": "ok"})

@router.post("/habit", response_model=HabitRead, status_code=status.HTTP_201_CREATED)
def create_habit(habit: HabitCreate, db: Session = Depends(get_db)):
    logger.info(f"Creating habit {habit.title}")
    existing = db.query(Habit).filter(Habit.title.ilike(habit.title.strip())).first()
    if existing:
        logger.warning(f"Habit {habit.title} already exists")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Habit with title '{habit.title}' already exists."
        )
    new_habit = Habit(**habit.dict())
    db.add(new_habit)
    db.commit()
    db.refresh(new_habit)
    logger.info(f"Created habit {habit.title} with id {new_habit.id}")
    return new_habit


# -------------------- CRUD Endpoints for Habit --------------------

@router.get("/habit", response_model=List[HabitRead])
def get_habits(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    logger.info(f"Retrieving habits {skip}/{limit}")
    return db.query(Habit).offset(skip).limit(limit).all()


@router.get("/habit/{habit_id}", response_model=HabitRead)
def get_habit(habit_id: str, db: Session = Depends(get_db)):
    logger.info(f"Retrieving habit {habit_id}")
    habit = db.query(Habit).filter(Habit.id == habit_id).first()
    if not habit:
        logger.info(f"Habit with id {habit_id} not found")
        raise HTTPException(status_code=404, detail="Habit not found")
    return habit


@router.put("/habit/{habit_id}", response_model=HabitRead)
def update_habit(habit_id: str, habit_update: HabitCreate, db: Session = Depends(get_db)):
    logger.info(f"Updating habit {habit_id}")
    habit = db.query(Habit).filter(Habit.id == habit_id).first()
    if not habit:
        logger.info(f"Habit with id {habit_id} not found")
        raise HTTPException(status_code=404, detail="Habit not found")

    existing = db.query(Habit).filter(Habit.title.ilike(habit_update.title.strip()), Habit.id != habit_id).first()
    if existing:
        logger.warning(f"Habit with id {habit_id} already exists")
        raise HTTPException(
            status_code=400,
            detail=f"Habit with title '{habit_update.title}' already exists."
        )

    for key, value in habit_update.dict().items():
        setattr(habit, key, value)
    db.commit()
    db.refresh(habit)
    logger.info(f"Updated habit {habit_id} with id {habit_id}")
    return habit


@router.delete("/habit/{habit_id}", status_code=status.HTTP_200_OK)
def delete_habit(habit_id: str, db: Session = Depends(get_db)):
    logger.info(f"Deleting habit {habit_id}")
    habit = db.query(Habit).filter(Habit.id == habit_id).first()
    if not habit:
        logger.warning(f"Habit with id {habit_id} not found")
        raise HTTPException(status_code=404, detail="Habit not found")
    db.delete(habit)
    db.commit()
    logger.info(f"Deleted habit {habit_id}")
    return {"message": f"Habit {habit_id} deleted successfully"}

app.include_router(router)